import type { LucideIcon } from "lucide-react";
import { cn } from "@/lib/utils";
import { TONE_CLASSES, type Tone } from "@/lib/tone";

/**
 * One operational figure.
 *
 * The tone is a top rule and a tinted icon holder, not a filled card: four
 * blocks of solid colour in a row would shout, and these are reference
 * numbers, not alerts. The label always says what the number means, so the
 * colour is only there to help the eye separate the four.
 */
export function KpiCard({
  label,
  value,
  detail,
  tone,
  icon: Icon,
}: {
  label: string;
  value: number | string;
  detail?: string;
  tone: Tone;
  icon: LucideIcon;
}) {
  const classes = TONE_CLASSES[tone];

  return (
    // The top rule is the one place the tone varies per instance, so it is set
    // from the token directly — a class name built at runtime would never be
    // generated by Tailwind's scanner.
    <div
      className="rounded-xl border border-t-2 bg-card p-4"
      style={{ borderTopColor: `var(--color-tone-${tone}-fg)` }}
    >
      <div className="flex items-start justify-between gap-2">
        <p className="text-xs text-muted-foreground">{label}</p>
        <span
          aria-hidden="true"
          className={cn("inline-flex size-7 items-center justify-center rounded-md", classes.avatar)}
        >
          <Icon className="size-3.5" />
        </span>
      </div>
      <p className="mt-1 font-serif text-2xl font-semibold tracking-tight tabular-nums">
        {value}
      </p>
      {detail && <p className="mt-0.5 text-xs text-muted-foreground">{detail}</p>}
    </div>
  );
}
