import { findOverlap, type TimeRange } from "./conflicts";

/**
 * Geometry and payloads for changing when a class happens.
 *
 * Everything here is pure: the calendar decides where a destination sits and what
 * it means, and the server decides whether it is allowed. Keeping the arithmetic
 * out of the components makes both testable without a browser or a database.
 */

/**
 * The interval every new scheduling selection lands on: :00 and :30.
 *
 * One constant for the whole product — the create-class form, a recurring slot, an
 * edit to a session's time and the calendar's move destinations all offer the same
 * starts, so staff never have to think about which screen they are on.
 *
 * It governs what can be *chosen*, not what may exist. Times already stored off the
 * half hour stay exactly as they are; see `startTimeOptions`.
 */
export const SCHEDULING_INTERVAL_MINUTES = 30;

const MINUTES_IN_DAY = 24 * 60;

export type MinuteRange = { startMinutes: number; durationMinutes: number };

/** "HH:MM" as minutes since midnight, or null when it is not a wall-clock time. */
export function parseWallClockMinutes(time: string): number | null {
  const match = /^([01]\d|2[0-3]):([0-5]\d)$/.exec(time);
  if (!match) return null;

  return Number(match[1]) * 60 + Number(match[2]);
}

/** Whether a start time sits on the scheduling interval. */
export function isAlignedStart(minutes: number): boolean {
  return minutes % SCHEDULING_INTERVAL_MINUTES === 0;
}

/**
 * Whether a wall-clock start time lands on the shared scheduling interval.
 *
 * The single alignment rule, in the form the server receives times in. The forms
 * only offer aligned times, but a server action is reachable without them, so this
 * is what actually decides — and both sides asking the same function is what keeps
 * "half past" meaning one thing across the product.
 */
export function isAlignedStartTime(time: string): boolean {
  const minutes = parseWallClockMinutes(time);

  return minutes !== null && isAlignedStart(minutes);
}

/**
 * Whether a scheduling edit may use this start time, given the one it has now.
 *
 * New times must be aligned. An existing time that is not — a class generated by an
 * older slot, or imported — stays allowed as long as it is being kept: changing
 * only the teacher, the date or the duration must not force a legacy class onto the
 * half hour, and nothing is ever rounded on the way through. The moment the start
 * time itself changes, the new one has to be aligned like any other.
 */
export function isStartTimeChangeAllowed(
  currentStartTime: string,
  submittedStartTime: string
): boolean {
  return submittedStartTime === currentStartTime || isAlignedStartTime(submittedStartTime);
}

/** The start of the interval a time falls inside, used to group an agenda by row. */
export function intervalStart(minutes: number): number {
  return Math.floor(minutes / SCHEDULING_INTERVAL_MINUTES) * SCHEDULING_INTERVAL_MINUTES;
}

export type StartTimeOption = { value: string; label: string };

/**
 * The start times a form may offer, given whatever the value currently is.
 *
 * Every half hour of the day, plus `current` when it is not one of them. Sessions
 * and slots created before this rule — or by an import — can start at 08:15, and
 * opening their form must not quietly round them: the existing time stays selected
 * and stays selectable, marked as the current value, until someone deliberately
 * picks an aligned one. Nothing is ever rewritten just by looking at it.
 */
export function startTimeOptions(current?: string | null): StartTimeOption[] {
  const options: StartTimeOption[] = [];

  for (let minutes = 0; minutes < MINUTES_IN_DAY; minutes += SCHEDULING_INTERVAL_MINUTES) {
    options.push({ value: formatSlotTime(minutes), label: formatSlotTime(minutes) });
  }

  const currentMinutes = current ? parseWallClockMinutes(current) : null;
  if (currentMinutes === null || isAlignedStart(currentMinutes)) {
    return options;
  }

  const preserved = {
    value: formatSlotTime(currentMinutes),
    label: `${formatSlotTime(currentMinutes)} (current)`,
  };
  const insertAt = options.findIndex(
    (option) => (parseWallClockMinutes(option.value) ?? 0) > currentMinutes
  );

  return insertAt === -1
    ? [...options, preserved]
    : [...options.slice(0, insertAt), preserved, ...options.slice(insertAt)];
}

/** Where a start time sits inside a day column, in pixels from its top. */
export function offsetFromMinutes(
  minutes: number,
  dayStartMinutes: number,
  pixelsPerHour: number
): number {
  return ((minutes - dayStartMinutes) / 60) * pixelsPerHour;
}

/**
 * Every start time a class of this length can occupy in the visible grid.
 * A class may not start so late that it would run past the last visible hour.
 */
export function slotStarts(
  startHour: number,
  endHour: number,
  durationMinutes: number
): number[] {
  const starts: number[] = [];
  const last = endHour * 60 - durationMinutes;

  for (
    let minutes = startHour * 60;
    minutes <= last;
    minutes += SCHEDULING_INTERVAL_MINUTES
  ) {
    starts.push(minutes);
  }

  return starts;
}

export type CalendarMode = "browse" | "moving";

/**
 * What the calendar's positions currently mean.
 *
 * The two things a position can be — "put the class being moved here" and "start a
 * new class here" — must never be offered at once, or a tap in the grid would be
 * ambiguous. Deriving both from one mode makes that impossible by construction
 * rather than by remembering to hide one of them.
 */
export function calendarMode(movingSessionId: string | null | undefined): CalendarMode {
  return movingSessionId ? "moving" : "browse";
}

/** Whether a position offers to start a new class there. */
export function offersCreation(mode: CalendarMode): boolean {
  return mode === "browse";
}

/** Whether a position offers itself as somewhere to move the selected class. */
export function offersMoveDestinations(mode: CalendarMode): boolean {
  return mode === "moving";
}

/**
 * A calendar position the user picked to create a class at.
 *
 * The label is carried along so the dialog can name the day without reformatting a
 * date the calendar has already formatted once.
 */
export type CreationSlot = {
  date: string;
  startMinutes: number;
  dayLabel: string;
};

/**
 * What a chosen position means to the server: a calendar date and a wall-clock
 * start time in the academy's timezone.
 *
 * The desktop grid and the phone agenda both go through here, so a position means
 * exactly the same thing on both. It is still only a request — the server converts
 * it, re-checks eligibility and re-checks the teacher's availability before
 * anything is written.
 */
export function creationInputFor(slot: CreationSlot): { date: string; startTime: string } {
  return { date: slot.date, startTime: formatSlotTime(slot.startMinutes) };
}

/**
 * Every position in the visible grid a new class can start at.
 *
 * Derived from the hours on screen and nothing else. In particular it does not
 * consult the sessions being displayed: two teachers can hold classes at the same
 * time, so an occupied-looking position is still a perfectly good one to create at.
 * Whether the chosen teacher is actually free is the server's question.
 */
export function creationStarts(startHour: number, endHour: number): number[] {
  return slotStarts(startHour, endHour, SCHEDULING_INTERVAL_MINUTES);
}

/**
 * Whether a card is drawn over this position.
 *
 * A layout question, not an availability one. It decides where the grid has room
 * to show the "Add class" label, and must never decide whether creating is
 * allowed there — that would quietly turn another teacher's class into a booked
 * time for everybody.
 */
export function isPositionCovered(startMinutes: number, sessions: MinuteRange[]): boolean {
  return (
    findOverlap(
      asRange({ startMinutes, durationMinutes: SCHEDULING_INTERVAL_MINUTES }),
      sessions.map(asRange)
    ) !== null
  );
}

/** A range that also knows which day it belongs to. */
export type DayMinuteRange = MinuteRange & { date: string };

/**
 * The teacher's booked time on one day, from their booked time for the week.
 *
 * The input is the teacher's own availability, never the sessions the calendar
 * happens to be drawing. Those are two different questions — "what am I showing"
 * and "when is this teacher busy" — and answering the second with the first is
 * what makes a filtered calendar report free time the teacher does not have.
 */
export function occupiedOnDate(busy: DayMinuteRange[], date: string): MinuteRange[] {
  return busy
    .filter((block) => block.date === date)
    .map((block) => ({
      startMinutes: block.startMinutes,
      durationMinutes: block.durationMinutes,
    }));
}

export type DestinationState = "original" | "conflict" | "free";

/**
 * Minute ranges within one day, expressed as instants on a shared synthetic day so
 * the calendar reuses the same overlap predicate the server enforces rather than
 * growing a second one that could drift from it.
 */
function asRange(range: MinuteRange): TimeRange {
  return {
    startsAt: new Date(range.startMinutes * 60_000),
    durationMinutes: range.durationMinutes,
  };
}

/**
 * What a destination means for the class being moved.
 *
 * `occupied` is the teacher's other time on that day, so this marks the same
 * double-bookings the server refuses. It is a preview, not the decision: the data
 * can go stale while move mode is open, so the server always re-checks before
 * anything is written.
 */
export function classifyDestination(
  candidate: MinuteRange,
  occupied: MinuteRange[],
  originalStartMinutes: number | null
): DestinationState {
  if (originalStartMinutes !== null && candidate.startMinutes === originalStartMinutes) {
    return "original";
  }

  return findOverlap(asRange(candidate), occupied.map(asRange)) ? "conflict" : "free";
}

/** A focused cell of the week grid: which day column, and which time down it. */
export type GridFocus = { dayIndex: number; startMinutes: number };

/**
 * Where an arrow key moves focus inside the week grid.
 *
 * A week of half hours is several hundred cells, which is far too many to tab
 * through, so both layers of the grid — the destinations of a move and the
 * positions a class can be created at — keep one tab stop and navigate with the
 * arrows. They share this function so the two never drift into behaving
 * differently under the same keys.
 *
 * Left and right change day and keep the time, because comparing the same hour
 * across the week is the reason to move sideways at all. Returns null for a key
 * this does not handle, which is the caller's signal to leave the event alone.
 */
export function moveGridFocus(
  current: GridFocus,
  key: string,
  dayCount: number,
  starts: number[]
): GridFocus | null {
  const slotIndex = starts.indexOf(current.startMinutes);
  if (slotIndex === -1 || current.dayIndex < 0 || current.dayIndex >= dayCount) {
    return null;
  }

  const atSlot = (index: number): GridFocus => ({
    dayIndex: current.dayIndex,
    startMinutes: starts[index] ?? current.startMinutes,
  });
  const atDay = (index: number): GridFocus => ({
    dayIndex: index,
    startMinutes: current.startMinutes,
  });

  switch (key) {
    case "ArrowDown": return atSlot(Math.min(slotIndex + 1, starts.length - 1));
    case "ArrowUp": return atSlot(Math.max(slotIndex - 1, 0));
    case "ArrowRight": return atDay(Math.min(current.dayIndex + 1, dayCount - 1));
    case "ArrowLeft": return atDay(Math.max(current.dayIndex - 1, 0));
    case "Home": return atSlot(0);
    case "End": return atSlot(starts.length - 1);
    default: return null;
  }
}

export type AgendaRow<T> = {
  startMinutes: number;
  sessions: T[];
  /** Whether this row offers the current mode's action: create here, or move here. */
  isActionable: boolean;
};

/**
 * One day laid out as a vertical list, for the phone agenda.
 *
 * Rows are the scheduling interval, so an action and the classes around it share
 * the same rhythm. A class is filed under the interval it starts inside rather than
 * the one it is aligned to, which keeps a legacy 08:15 class visible in the 08:00
 * row instead of vanishing between two half hours.
 *
 * `actionableStarts` is whatever the current mode offers — every position of the
 * day while browsing, or the destinations a class can move to. Intervals with
 * neither a class nor an action are left out, so a day is never padded with rows
 * that do nothing.
 */
export function buildAgendaRows<T extends { startMinutes: number }>(
  sessions: T[],
  actionableStarts: number[]
): AgendaRow<T>[] {
  const actionable = new Set(actionableStarts);
  const rowStarts = new Set<number>(actionable);
  for (const session of sessions) {
    rowStarts.add(intervalStart(session.startMinutes));
  }

  return [...rowStarts]
    .sort((a, b) => a - b)
    .map((startMinutes) => ({
      startMinutes,
      sessions: sessions
        .filter((session) => intervalStart(session.startMinutes) === startMinutes)
        .sort((a, b) => a.startMinutes - b.startMinutes),
      isActionable: actionable.has(startMinutes),
    }));
}

/** Minutes since midnight as the "HH:MM" wall-clock time the server expects. */
export function formatSlotTime(minutes: number): string {
  const hours = Math.floor(minutes / 60);
  const remainder = minutes % 60;

  return `${String(hours).padStart(2, "0")}:${String(remainder).padStart(2, "0")}`;
}

/**
 * When a class of this length starting here would end, as a wall-clock label.
 *
 * Wraps at midnight so a late class reads as "00:30" rather than "24:30". It is a
 * label only: the stored instant is computed on the server from the date and start
 * time, so nothing about the class depends on this.
 */
export function endTimeLabel(startMinutes: number, durationMinutes: number): string {
  return formatSlotTime((startMinutes + durationMinutes) % MINUTES_IN_DAY);
}

export type SchedulingUpdate = {
  startsAt: Date;
  durationMinutes: number;
  teacherId: string;
};

/**
 * The only fields a scheduling change is allowed to write.
 *
 * Built explicitly so a move can never reach the recurring pattern: `scheduleSlotId`
 * and `slotOccurrenceOn` are absent, which keeps regeneration treating the
 * occurrence as done, and nothing here can touch the ScheduleSlot itself or the
 * student's primary teacher.
 */
export function buildSchedulingUpdate(params: SchedulingUpdate): SchedulingUpdate {
  return {
    startsAt: params.startsAt,
    durationMinutes: params.durationMinutes,
    teacherId: params.teacherId,
  };
}

/**
 * A calendar link. Move mode lives in the URL so it survives navigating to another
 * week, and so cancelling it is just going back to the calendar without it.
 */
export function calendarUrl(params: {
  week: string;
  teacher?: string;
  moving?: string;
}): string {
  const query = new URLSearchParams({ week: params.week });
  if (params.teacher) query.set("teacher", params.teacher);
  if (params.moving) query.set("moving", params.moving);

  return `/calendar?${query.toString()}`;
}
