import type { Metadata, Viewport } from "next";
import { Instrument_Sans, Newsreader } from "next/font/google";
import "./globals.css";

/*
 * Two roles, two faces, nothing else.
 *
 * Instrument Sans carries everything operational: navigation, tables, forms,
 * badges, data. Newsreader is the editorial voice — the wordmark, the greeting
 * and page titles — and appears nowhere else, which is what keeps it feeling
 * deliberate rather than decorative.
 *
 * Both are self-hosted by next/font at build time, so there is no external
 * request and no layout shift beyond the swap.
 */
const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  display: "swap",
});

const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "DARPE Admin",
  description: "Internal administration for DARPE Global.",
  applicationName: "DARPE",
  /*
   * `apple-icon.png` and `favicon.ico` beside this file are picked up by
   * convention; the manifest is generated by `manifest.ts`. What is left is
   * what only iOS reads:
   *
   * - `appleWebApp.capable` removes Safari's chrome when staff add DARPE to
   *   their home screen. Without it the app opens in a browser tab however it
   *   was installed.
   * - `statusBarStyle` keeps the status bar legible over the lavender ground.
   *
   * No `startupImage` here on purpose: a single portrait PNG declared as a
   * universal launch image is stretched on every device it does not match, and
   * doing it properly needs one file per device with matching media queries.
   * The splash rasters in `public/brand/` are ready for that when DARPE says
   * which devices matter.
   */
  appleWebApp: {
    capable: true,
    title: "DARPE",
    statusBarStyle: "default",
  },
  formatDetection: {
    // Student phone numbers are data, not links to dial from an admin table.
    telephone: false,
  },
};

/**
 * `viewport-fit=cover` is what makes `env(safe-area-inset-*)` report real values.
 * Without it those insets are always 0, so the bottom navigation and the dialog
 * footer would sit under a phone's home indicator no matter what padding asked for.
 */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  // Tints the browser and installed-window chrome to match the app.
  themeColor: "#482d79",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.variable} ${newsreader.variable} h-full antialiased`}
    >
      {/*
        A definite height all the way down — html, body, then the app shell —
        so the shell is exactly the viewport and nothing can push the document
        past it. `min-h-full` let the body grow a few pixels beyond the shell,
        which produced a second scrollbar next to the one inside `main`.
        Deliberately not `overflow-hidden`: the login page is free to scroll if
        its card ever outgrows a small screen.
      */}
      <body className="h-full">{children}</body>
    </html>
  );
}
