/**
 * The iPhone launch images an installed DARPE shows while its first page
 * loads — mostly the moment after a few idle hours, when the server takes a
 * second or two to wake up.
 *
 * iOS never scales a launch image: it picks the one whose media query matches
 * the device exactly, and shows white if none does. So there is one file per
 * screen size in use, generated by `scripts/build-splash.mjs` into
 * `public/brand/splash/`. Keep this list and that script's in step — a size
 * here without its file is a broken link, a file without its entry is never
 * shown.
 *
 * Android needs none of this: Chrome builds its own launch screen from the
 * manifest's name, icon and background colour.
 */
import type { Metadata } from "next";

type AppleWebApp = Exclude<Metadata["appleWebApp"], boolean | null | undefined>;

const SCREENS = [
  { width: 440, height: 956, ratio: 3 }, // 16 Pro Max, 17 Pro Max
  { width: 402, height: 874, ratio: 3 }, // 16 Pro, 17, 17 Pro
  { width: 420, height: 912, ratio: 3 }, // Air
  { width: 430, height: 932, ratio: 3 }, // 14 Pro Max, 15 Plus / Pro Max, 16 Plus
  { width: 393, height: 852, ratio: 3 }, // 14 Pro, 15, 15 Pro, 16
  { width: 428, height: 926, ratio: 3 }, // 12 / 13 Pro Max, 14 Plus
  { width: 390, height: 844, ratio: 3 }, // 12, 13, 14, 16e
  { width: 375, height: 812, ratio: 3 }, // X, XS, 11 Pro, 12 / 13 mini
  { width: 414, height: 896, ratio: 3 }, // XS Max, 11 Pro Max
  { width: 414, height: 896, ratio: 2 }, // XR, 11
  { width: 375, height: 667, ratio: 2 }, // SE (2nd and 3rd), 8
] as const;

export const SPLASH_SCREENS: AppleWebApp["startupImage"] = SCREENS.map(
  ({ width, height, ratio }) => ({
    url: `/brand/splash/iphone-${width * ratio}x${height * ratio}.png`,
    media:
      `(device-width: ${width}px) and (device-height: ${height}px) and ` +
      `(-webkit-device-pixel-ratio: ${ratio}) and (orientation: portrait)`,
  })
);
